apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.simpleweb.name }}
  namespace: default
  labels:
    app: {{ .Values.simpleweb.name }}
spec:
  replicas: {{ .Values.simpleweb.minReplicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.simpleweb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.simpleweb.name }}
    spec:
      containers:
      - name: {{ .Values.simpleweb.name }}
        image: {{ .Values.global.registry }}/{{ .Values.simpleweb.name }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.simpleweb.port }}
          name: {{ .Values.simpleweb.name }}
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 800m

---

kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.simpleweb.name }}-service
  namespace: default
spec:
  selector:
    app: {{ .Values.simpleweb.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.simpleweb.port }}
      targetPort: {{ .Values.simpleweb.port }}

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: {{ .Values.simpleweb.name }}-service
          servicePort: {{ .Values.simpleweb.port }}

---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: memory-cpu-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: {{ .Values.simpleweb.name }}
  triggers:
  - type: memory
    metadata:
      type: Utilization
      value: "150"
  - type: cpu
    metadata:
      type: Utilization
      value: "150"
  - type: cron
    metadata:
      timezone: Asia/Jerusalem
      start: 0 8 * * *
      end: 0 12 * * *
      desiredReplicas: "3"
